package com.mayunfei.downloadmanager.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mayunfei.downloadmanager.db.BundleBean;
import com.mayunfei.downloadmanager.db.ErrorLog;
import com.mayunfei.downloadmanager.db.ItemBean;

import com.mayunfei.downloadmanager.db.greendao.BundleBeanDao;
import com.mayunfei.downloadmanager.db.greendao.ErrorLogDao;
import com.mayunfei.downloadmanager.db.greendao.ItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bundleBeanDaoConfig;
    private final DaoConfig errorLogDaoConfig;
    private final DaoConfig itemBeanDaoConfig;

    private final BundleBeanDao bundleBeanDao;
    private final ErrorLogDao errorLogDao;
    private final ItemBeanDao itemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bundleBeanDaoConfig = daoConfigMap.get(BundleBeanDao.class).clone();
        bundleBeanDaoConfig.initIdentityScope(type);

        errorLogDaoConfig = daoConfigMap.get(ErrorLogDao.class).clone();
        errorLogDaoConfig.initIdentityScope(type);

        itemBeanDaoConfig = daoConfigMap.get(ItemBeanDao.class).clone();
        itemBeanDaoConfig.initIdentityScope(type);

        bundleBeanDao = new BundleBeanDao(bundleBeanDaoConfig, this);
        errorLogDao = new ErrorLogDao(errorLogDaoConfig, this);
        itemBeanDao = new ItemBeanDao(itemBeanDaoConfig, this);

        registerDao(BundleBean.class, bundleBeanDao);
        registerDao(ErrorLog.class, errorLogDao);
        registerDao(ItemBean.class, itemBeanDao);
    }
    
    public void clear() {
        bundleBeanDaoConfig.clearIdentityScope();
        errorLogDaoConfig.clearIdentityScope();
        itemBeanDaoConfig.clearIdentityScope();
    }

    public BundleBeanDao getBundleBeanDao() {
        return bundleBeanDao;
    }

    public ErrorLogDao getErrorLogDao() {
        return errorLogDao;
    }

    public ItemBeanDao getItemBeanDao() {
        return itemBeanDao;
    }

}
